[build]
  command = "npm install && npm run start"
  publish = "."

[context.production.environment]
  NODE_VERSION = "14"  # or the version your project requires

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"