[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "14"  # or the version your project requires

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200